
# Site settings
url: "http://localhost:4000/"
baseurl: "parc_botannia"
name : Parc Botannia
brand : Parc Botannia
description : This is the description of my project
keyword :
year : 2016
exclude :
  - node_modules


#Sass
sass:
  style: compressed
